print(" - Loading Piotr config")
require("work.remap")
print("   - remap")
require("work.packer")
print("   - packer")
require("work.set")
print("   - sets")
require("config.telescope.multigrep")
print("   - custom plugins")
print(" - Loaded Piotr config")
